# @package _group_

category: church_outdoor
resolution: 256

train: ${datasets.test}
val: ${datasets.test}
test:
  - dataset_name: train
    inception_real_stats_path: ${hydra:runtime.cwd}/inception_stats/lsun_${datasets.category}_${datasets.resolution}.npz
    dataset_class:
      _target_: dinr.utils.lmdb.LmdbDataset
      path: ${hydra:runtime.cwd}/data/lsun/${datasets.category}_train_lmdb
      max_readers: 32
      transform: ${datasets._transform}

_transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size: ${datasets.resolution}
      interpolation: 1 # PIL.Image.LANCZOS
    - _target_: torchvision.transforms.CenterCrop
      size: ${datasets.resolution}
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
