# @package _group_

generator:
  _target_: dinr.modeling.INRGenerator
  style_dim: 512
  n_mlp: 8
  num_channels: 512
  num_layers: 15
  fourier_mapping:
    _target_: dinr.modeling.FourierMapping
    in_features: 2
    out_features: 512
    scale: 2.1213203435596424 # np.sqrt(9 / in_features)
    learnable: true
    init: uniform
    compute_sin: true
    compute_cos: false
  lr_mlp: 0.01
  factorization_rank: ~
  use_sigmoid: false
  skip_connections: false

discriminator:
  _target_: dinr.modeling.Discriminator
  size: 256
  channel_multiplier: 2
  blur_kernel: [1, 3, 3, 1]