# @package _group_

generator:
  _target_: dinr.modeling.Generator
  size: 256
  style_dim: 512
  n_mlp: 8
  channel_multiplier: 2
  blur_kernel: [1, 3, 3, 1]
  lr_mlp: 0.01
  factorization_rank: ~

discriminator:
  _target_: dinr.modeling.Discriminator
  size: 256
  channel_multiplier: 2
  blur_kernel: [1, 3, 3, 1]
