generator:
  width: 128
  num_layers: 4
  perturb: 1.0
  raw_noise_std: 1.0
  n_samples: 32
  n_importance: 32
  white_bkgd: true
  patch_size: 64

  fmm:
    enabled: true
    rank: 10
    activation: demod

loss_kwargs:
  r1_gamma: 1.0
  pl_weight: 0
  style_mixing_prob: 0.0

discriminator:
  fmaps: 1

