generator:
  width: 128
  num_layers: 8
  perturb: 1.0
  raw_noise_std: 1.0
  n_samples: 32
  n_importance: 0
  white_bkgd: true
  patch_size: 32
  phi_low: -2
  phi_high: 2
  use_normal: true
  theta_std: 5
  render_size: 1.0
  shift: 0.0

  fmm:
    enabled: true
    rank: 10
    activation: demod

loss_kwargs:
  r1_gamma: 0.1
  pl_weight: 0
  style_mixing_prob: 0.0

discriminator:
  fmaps: 1

